# Generated by Django 5.2.7 on 2025-10-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="cart",
            managers=[],
        ),
    ]
