# Generated by Django 5.2.7 on 2025-10-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_aboutcontact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutdelivery",
            options={
                "verbose_name": "Оплата и доставка",
                "verbose_name_plural": "Оплата и доставка",
            },
        ),
        migrations.AlterModelOptions(
            name="aboutpage",
            options={"verbose_name": "О нас", "verbose_name_plural": "О нас"},
        ),
        migrations.AlterModelTable(
            name="aboutdelivery",
            table="delivery",
        ),
        migrations.AlterModelTable(
            name="aboutpage",
            table="about",
        ),
    ]
